### ISSUE TITLE
Running calculation

### ISSUE THREAD

**Issue by asuda** [devillemereuil/bayescenv#1]
Hi,

I am using BayeScEnv-0.3 with Mac (ver.10.8.5) and trying to analyse for detecting outliers which associated with environmental variables.
I am now using test files that are in a directory called "test" which was included in  bayescenv-0.3 package. but when I started to run the analysis under terminal, there seems to be an error and says "Abort trap: 6". and then I also used GUI, calculation freezes in the middle of analysis.
What might be a problem here? is that my computer? or the command I used was incorrect?
I use a command in below 
./bayescenv data.txt -env env.txt -out_pilot -all_trace -unif_pr 10 -pr_jump 0.1 -pr_pref 0.5 -o test -burn 3000 -thin 10 -nbp 10 -pilot 2000

Thanks in advance for any suggestions.

Ayako

**Comment by devillemereuil** [comment]
Hi!

Yes, it seems the binary for Mac OS X was somehow corrupted. I've compiled and uploaded new binaries, which are packed in a new release (v0.4) on the Releases page:
https://github.com/devillemereuil/bayescenv/releases

Would you mind trying this new release and telling me whether the bug is fixed?

Cheers,
Pierre.

**Comment by devillemereuil** [comment]
Fixed with the new binaries.
