### ISSUE TITLE
Methods question

### ISSUE THREAD

**Issue by Astahlke** [devillemereuil/bayescenv#5]
Hi there, 

Can you provide some more details about how missing data are handled in this software? I'm guessing that since the method utlimately uses the allele counts, missing data are essentially ignored. 

Thank you!

Amanda

**Comment by devillemereuil** [comment]
Hi,

Missing data should actually be dealt with upstream of BayeScEnv, since the method uses allele counts as data. But you are right, missing data are usually censored in the allele counts. Although not a problem is they are missing at random, this could create some issues in the case of allele dropout with a mechanism linked to the allele frequencies themselves.

A way around this could be to impute missing data before computing the allele counts, although this can be quite complex, depending on the way the data were generated (e.g. for RAD/GBS).

**Comment by Astahlke** [comment]
Got it - thanks!
